# Generated by Django 5.2.4 on 2025-07-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=500)),
                ('customer_name', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('waypoint_type', models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], max_length=20)),
                ('transport_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='TransportApp.transportorder')),
            ],
        ),
    ]
